### ISSUE TITLE
Mutation procedure should support table records as input.

### ISSUE THREAD

**Issue by nil1511** [graphile/graphile-build#132]
Hello, 
Thank you for the amazing library. I ran into some issue while creating custom mutation using Postgres procedure.
eg 
```sql
CREATE TABLE customers (
    customer_id   INTEGER UNIQUE,
    customer_name VARCHAR(50),
    phone         CHAR(8)
);

CREATE TABLE project (
    name VARCHAR(50),
    customer_id INTEGER references customers(customer_id)
);
```
and if we create a customer using custom procedure as 
```sql
CREATE OR REPLACE function create_customers_and_project(customer_record customer,project_record project) returns project as $$
  DECLARE
new_customer_id integer;
new_project project;
  begin
  INSERT INTO "public"."customers"("customer_id", "customer_name", "phone") 
  VALUES(customer_record.customer_id, customer_record.customer_name, customer_record.phone) returning customer_id into new_customer_id;

  INSERT INTO "public"."project"("name", "customer_id") 
  VALUES(project_record.name, new_customer_id) returning * into new_project;
  return new_project;
  end;
$$ language plpgsql VOLATILE;
```

The new procedure `createCustomersAndProject` does not appear in the schema. 
I think [this](https://github.com/graphile/graphile-build/blob/83abbb84d62415a6ff455426e9424a61d95a815b/packages/graphile-build-pg/src/plugins/PgMutationProceduresPlugin.js#L40) condition is responsible for excluding the procedure from the schema. Should this condition be in schema?

Thank you.

**Comment by benjie** [comment]
(See also: https://github.com/postgraphql/postgraphql/issues/649)

Yep, I was planning to reserve this in case we come up with a way of doing computed column setters, but TBH I think we should find a different way of doing that since this is a more obvious use case.

If you fancy doing a PR for this, please remove the entire `if` statement you link to and add a suitable function to https://github.com/graphile/graphile-build/blob/master/packages/postgraphile-core/__tests__/kitchen-sink-schema.sql so that the new function appears in the schema test snapshots. 👍

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["Computed Column" mutation bug](https://trello.com/c/snywsATv/24-computed-column-mutation-bug)
