### ISSUE TITLE
query error on unordered set when using ordered db function

### ISSUE THREAD

**Issue by cdaringe** [graphile/graphile-build#155]
# problem

an error is produced regarding missing ordering when querying an ordered set

```sql
-- almost directly out of the graphile examples
create function search_topics(search text)
returns setof topics as $$
  select *
  from topics
  where
    name ilike ('%' || search || '%') or
    description ilike ('%' || search || '%')
  order by 1
$$ language sql stable;
```
note--there is an `order by` clause.

now, running the following query

```graphql
{
  searchTopics(search: "c", last: 1) {
    nodes {
      id
    }
  }
}
```

(note the `last` entry.  im trying to learn how use Cursors here :))

produces the following error:

```json
{
  "errors": [
    {
      "message": "Cannot do last of an unordered set",
      ...
      "path": [
        "searchTopics"
      ]
}
```

# discussion

do one of the graphile-build plugins need to detect orderedness so we can paginate on searches?

**Comment by cdaringe** [comment]
perhaps as a workaround:

`create function search_topics(search text, off int)`

`searchTopics(search: "c", off: 5) {`

may work.

**Comment by benjie** [comment]
SQL functions are a black box to us. 

Normally when we perform “last:5” we invert the order statements (asc becomes desc) and take the *first* 5 result (via “limit 5”) and then we flip the results again so they’re in the right order.

We’re unable to perform this ASC/DESC inversion within a function so we cannot do last. We could query the entire thing and return the last 5 rows queried but given the function may return billions of rows that would be quite inefficient! Instead I’m afraid you’re stuck with first/offset (limit/offset).

SQL functions do not currently get an orderBy field in GraphQL because we assume that the writer orders them; however we may add an optional one in a future release.

**Comment by cdaringe** [comment]
This makes good sense.  Thanks
