### ISSUE TITLE
Inflection design is not extensible

### ISSUE THREAD

**Issue by mzabaluev** [graphile/graphile-build#198]
The `pgInflection` context object that is passed to the plugins in `graphile-build-pg` provides name mapping functions used by the plugins in that package. If a third-party plugin needs its own mapping function, it would be nice to use the same `InflectorUtils` function table that the inflector object uses in order to conform to the same naming rules, but that is not available from the inflector object.

**Comment by benjie** [comment]
I've got an issue for that on my personal Trello board as it happens: "Add inflection type adder (e.g. graphql-build-pg should add it's own inflectors)"

Also need to expose the inflector more easily for overriding, it's a bit of a pain currently (hence undocumented).

**Comment by benjie** [comment]
This is fixed in master; the old inflection API is now deprecated / unsupported.

The initial inflection starts like this:

https://github.com/graphile/graphile-build/blob/cb883131af49ed2ca3b06d428337b2f58892c3d9/packages/graphile-build/src/makeNewBuild.js#L671-L677

And you can expand it via a plugin like this:

https://github.com/graphile/graphile-build/blob/cb883131af49ed2ca3b06d428337b2f58892c3d9/packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js#L57-L407
